[pytest]
testpaths = tests
pythonpath = .
# addopts = -q --tb=line
addopts = -s -v --tb=line
log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s:%(name)s:%(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_level = INFO
console_output_style = classic
markers =
    integration: marks tests as integration (deselect with '-m "not integration"')
    minio: test minio
